import { alpha, styled } from "@mui/material/styles";
import { Box, Paper } from "@mui/material";

export const EditorShell = styled(Paper, { shouldForwardProp: (prop) => prop !== "fullscreen" })<{ fullscreen?: boolean }>(({ theme, fullscreen }) => ({
  minHeight: 280,
  display: "flex",
  flexDirection: "column",
  overflow: "hidden",
  borderRadius: 0,
  border: 0,
  boxShadow: "none",
  background: theme.palette.background.paper,
  ...(fullscreen && {
    height: "100%",
  }),
}));

export const EditorCanvas = styled(Box)(({ theme }) => ({
  flex: "1 1 auto",
  overflow: "hidden",
  backgroundColor: theme.palette.background.paper,
  ".moxu-editor-dropcursor": {
    visibility: "hidden",
    borderRadius: 999,
    boxShadow: `0 0 0 1px ${alpha(theme.palette.primary.main, .12)}`,
  },
  "&.is-block-dragging .moxu-editor-dropcursor": { visibility: "visible" },
  "&.is-content-scrolling [data-block-control]": { opacity: "0 !important", pointerEvents: "none" },
  "&.is-block-dragging [data-block-control]": { opacity: "0 !important" },
  ".moxu-editor-content": {
    display: "flex",
    flex: "1 1 auto",
    overflowY: "auto",
    flexDirection: "column",
    scrollbarWidth: "thin",
    scrollbarColor: `${alpha(theme.palette.text.disabled, .35)} ${alpha(theme.palette.text.disabled, .08)}`,
    "&::-webkit-scrollbar": { width: 7 },
    "&::-webkit-scrollbar-track": { background: "transparent" },
    "&::-webkit-scrollbar-thumb": { background: alpha(theme.palette.text.disabled, .3), borderRadius: 99 },
    transform: "translateZ(0)",
    willChange: "transform",
    contain: "paint",
  },
  ".tiptap": {
    minHeight: "inherit",
    width: "100%",
    maxWidth: 760,
    marginInline: "auto",
    padding: theme.spacing(0, 3.25, 8),
    outline: "none",
    color: theme.palette.text.primary,
    caretColor: theme.palette.text.primary,
    "> *:first-child": { marginTop: 0 },
    "> *:last-child": { marginBottom: 0 },
    "> * + *": { marginTop: ".75em" },
    "*::selection": { backgroundColor: alpha(theme.palette.grey[900], .1) },
    h1: { fontSize: "1.875rem", lineHeight: 1.25, fontWeight: 800, marginTop: "3rem", marginBottom: 0 },
    h2: { fontSize: "1.5rem", lineHeight: 1.3, fontWeight: 800, marginTop: "3rem", marginBottom: 0 },
    h3: { fontSize: "1.25rem", lineHeight: 1.35, fontWeight: 800, marginTop: "3rem", marginBottom: 0 },
    h4: { fontSize: "1.125rem", lineHeight: 1.4, fontWeight: 800, marginTop: "2rem", marginBottom: 0 },
    h5: { fontSize: "1rem", lineHeight: 1.5, fontWeight: 800, marginTop: "2rem", marginBottom: 0 },
    h6: { fontSize: ".875rem", lineHeight: 1.5, fontWeight: 800, marginTop: "2rem", marginBottom: 0 },
    "h1:first-of-type, h2:first-of-type, h3:first-of-type, h4:first-of-type, h5:first-of-type, h6:first-of-type": { marginTop: 0 },
    p: { ...theme.typography.body1, lineHeight: 1.625, marginTop: ".75rem", marginBottom: ".75rem" },
    "> p": { marginTop: "1.5rem", marginBottom: "1.5rem" },
    "> p:first-of-type": { marginTop: 0 },
    "> p:last-of-type": { marginBottom: 0 },
    a: { color: theme.palette.primary.main, textDecorationColor: alpha(theme.palette.primary.main, 0.4), textUnderlineOffset: 3 },
    hr: { border: 0, borderBottom: `1px solid ${theme.palette.divider}`, margin: "2em 0" },
    "ul, ol": { padding: "0 2rem", marginTop: "1.5rem", marginBottom: "1.5rem" },
    li: { lineHeight: 1.9 },
    "li > p": { margin: 0 },
    "ul[data-type=taskList]": { listStyle: "none", paddingLeft: 0, "li": { display: "flex", gap: 8, alignItems: "flex-start" }, "label": { paddingTop: 5 }, "input": { accentColor: theme.palette.primary.main } },
    ".tableWrapper": { width: "100%", maxWidth: "100%", overflowX: "auto", overflowY: "hidden", position: "relative", marginTop: "2.5rem", marginBottom: "2.5rem", padding: 0, overscrollBehaviorX: "contain", scrollbarWidth: "none", "&::-webkit-scrollbar": { display: "none" } },
    table: {
      width: "100%",
      tableLayout: "fixed",
      borderCollapse: "collapse",
      overflow: "hidden",
      borderColor: alpha(theme.palette.common.black, .12),
      borderRadius: ".35rem",
      boxSizing: "border-box",
      "th, td": { minWidth: 100, padding: theme.spacing(1, 1.25), position: "relative", textAlign: "left", verticalAlign: "top", border: `1px solid ${alpha(theme.palette.common.black, .12)}`, transition: "background-color .12s ease, box-shadow .12s ease" },
      th: { color: theme.palette.text.primary, backgroundColor: alpha(theme.palette.primary.main, .075), borderBottomColor: alpha(theme.palette.primary.main, .24), fontWeight: 800 },
      "tr:nth-of-type(even) td": { backgroundColor: alpha(theme.palette.grey[500], .025) },
      "td p, th p": { margin: 0, lineHeight: 1.55 },
      "td p + p, th p + p": { marginTop: ".75rem" },
      "td[data-active-table-cell], th[data-active-table-cell]": { zIndex: 1, boxShadow: `inset 0 0 0 2px ${alpha(theme.palette.primary.main, .72)}`, backgroundColor: alpha(theme.palette.primary.main, .045) },
      ".selectedCell": { zIndex: 1, backgroundColor: `${alpha(theme.palette.primary.main, .1)} !important`, "&::after": { content: '""', position: "absolute", inset: 0, zIndex: 2, pointerEvents: "none", backgroundColor: alpha(theme.palette.primary.main, .1), boxShadow: `inset 0 0 0 1.5px ${alpha(theme.palette.primary.main, .7)}` } },
      ".column-resize-handle": { position: "absolute", top: 0, right: 0, bottom: 0, zIndex: 4, width: 3, pointerEvents: "none", border: 0, backgroundColor: alpha(theme.palette.primary.main, .58), boxShadow: `0 0 0 1px ${alpha(theme.palette.background.paper, .85)}` },
    },
    "&.resize-cursor, &.resize-cursor *": { cursor: "col-resize !important" },
    blockquote: {
      width: "100%",
      maxWidth: 680,
      position: "relative",
      margin: "24px auto",
      padding: theme.spacing(3, 3, 3, 8),
      borderLeft: `8px solid ${alpha(theme.palette.grey[500], 0.12)}`,
      color: theme.palette.text.secondary,
      fontFamily: "Georgia, serif",
      fontSize: "1.35em",
      lineHeight: 1.55,
      "&::before": { content: '"“"', position: "absolute", left: 16, top: -8, color: theme.palette.text.disabled, fontSize: "3em" },
      p: { margin: 0, font: "inherit" },
    },
    code: { padding: theme.spacing(0.25, 0.5), borderRadius: 5, color: theme.palette.text.secondary, background: alpha(theme.palette.grey[500], 0.18), fontSize: theme.typography.body2.fontSize },
    pre: { overflowX: "auto", padding: theme.spacing(3), borderRadius: theme.shape.borderRadius, color: theme.palette.common.white, background: theme.palette.grey[900] },
    "pre code": { padding: 0, color: "inherit", background: "transparent" },
    "p.is-editor-empty:first-of-type::before": { content: "attr(data-placeholder)", float: "left", height: 0, pointerEvents: "none", color: theme.palette.text.disabled },
    "aside[data-mdx-callout]": {
      margin: "28px 0",
      padding: theme.spacing(2.25, 2.5),
      borderRadius: theme.shape.borderRadius,
      border: `1px solid ${alpha(theme.palette.primary.main, 0.2)}`,
      borderLeft: `4px solid ${theme.palette.primary.main}`,
      background: alpha(theme.palette.primary.main, 0.06),
      "p:first-of-type": { marginBottom: 6, color: theme.palette.primary.main, fontWeight: 750, fontSize: 13 },
      "p:last-of-type": { marginBottom: 0 },
    },
    "span[data-mdx-badge]": {
      display: "inline-flex",
      padding: "2px 8px",
      borderRadius: 99,
      color: theme.palette.primary.main,
      background: alpha(theme.palette.primary.main, 0.12),
      fontSize: ".75em",
      fontWeight: 750,
    },
    "span[data-mdx-badge][data-tone=success]": { color: "#187A55", background: "#DCF5E8" },
    "section[data-mdx-card] .card-content": { display: "block", padding: theme.spacing(2, 2.25), "h1, h2, h3, h4, h5, h6": { margin: 0, fontSize: "1.1rem", lineHeight: 1.45 }, "h1 + p, h2 + p, h3 + p, h4 + p, h5 + p, h6 + p": { marginTop: theme.spacing(1.25) }, "p:last-child": { marginBottom: 0 } },
    "details[data-mdx-details]": { margin: "24px 0", overflow: "hidden", border: `1px solid ${theme.palette.divider}`, borderRadius: 12, bgcolor: theme.palette.background.paper, "summary": { cursor: "pointer", listStyle: "none", fontWeight: 750, padding: theme.spacing(1.5, 2), background: alpha(theme.palette.grey[500], .06), "&::-webkit-details-marker": { display: "none" }, "&::before": { content: '"›"', display: "inline-block", marginRight: 10, color: theme.palette.text.secondary, transition: "transform .15s ease" } }, "&[open] summary::before": { transform: "rotate(90deg)" }, "> div": { padding: theme.spacing(1.5, 2), borderTop: `1px solid ${theme.palette.divider}` }, "p:first-child": { marginTop: 0 }, "p:last-child": { marginBottom: 0 } },
    "section[data-mdx-highlight]": { margin: "24px 0", padding: theme.spacing(2), borderRadius: 12, border: "1px solid #F5D67B", bgcolor: "#FFF8DF", "p:last-child": { marginBottom: 0 } },
    "section[data-mdx-highlight][data-tone=blue]": { borderColor: "#B2CCFF", bgcolor: "#EFF4FF" },
    "section[data-mdx-highlight][data-tone=green]": { borderColor: "#A9EFC5", bgcolor: "#ECFDF3" },
    "hr[data-mdx-divider]": { margin: "30px 0", border: 0, height: 2, background: alpha(theme.palette.grey[500], .3) },
    "hr[data-mdx-divider][variant=dashed]": { height: 0, borderTop: `2px dashed ${alpha(theme.palette.grey[500], .35)}`, background: "none" },
    "hr[data-mdx-divider][variant=dotted]": { height: 0, borderTop: `3px dotted ${alpha(theme.palette.grey[500], .35)}`, background: "none" },
    "hr[data-mdx-divider][variant=double]": { height: 5, borderTop: `1px solid ${alpha(theme.palette.grey[500], .35)}`, borderBottom: `1px solid ${alpha(theme.palette.grey[500], .35)}`, background: "none" },
    "hr[data-mdx-divider][variant=gradient]": { background: `linear-gradient(90deg, transparent, ${theme.palette.primary.main}, transparent)` },
    "hr[data-mdx-divider][variant=ornament]": { height: 1, overflow: "visible", background: alpha(theme.palette.grey[500], .3), "&::after": { content: '"◆"', display: "block", width: 28, margin: "-9px auto 0", textAlign: "center", color: theme.palette.primary.main, background: theme.palette.background.paper } },
    ".ProseMirror-selectednode": { outline: `1.5px solid ${alpha(theme.palette.primary.main, .78)}`, outlineOffset: 2 },
  },
}));
